In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

1.Create two 3×3 matrices with random integers in Python.

In [2]:
matrix_1 = np.random.randint(1, 10, (3, 3))
matrix_2 = np.random.randint(1, 10, (3, 3))

print("Matrix 1:")
print(matrix_1)
print("\nMatrix 2:")
print(matrix_2)

Matrix 1:
[[3 1 5]
 [9 5 8]
 [3 8 1]]

Matrix 2:
[[9 5 5]
 [2 2 5]
 [7 8 8]]


2. Perform addition, subtraction, and multiplication operations on these matrices.


In [3]:
# Addition
matrix_sum = np.add(matrix_1, matrix_2)
print("\nMatrix Sum:")
print(matrix_sum)

# Subtraction
matrix_difference = np.subtract(matrix_1, matrix_2)
print("\nMatrix Difference:")
print(matrix_difference)

# Multiplication
matrix_product = np.dot(matrix_1, matrix_2)
print("\nMatrix Product:")
print(matrix_product)


Matrix Sum:
[[12  6 10]
 [11  7 13]
 [10 16  9]]

Matrix Difference:
[[-6 -4  0]
 [ 7  3  3]
 [-4  0 -7]]

Matrix Product:
[[ 64  57  60]
 [147 119 134]
 [ 50  39  63]]


3. Compute the determinant, inverse, and rank of one of the matrices.

In [4]:
# Determinant of Matrix 1
determinant_matrix1 = np.linalg.det(matrix_1)
print("\nDeterminant of Matrix 1:")
print(determinant_matrix1)

# Inverse of Matrix 1 using if-else
if not np.isclose(determinant_matrix1, 0): # Check if determinant is not close to zero
    inverse_matrix1 = np.linalg.inv(matrix_1)
    print("\nInverse of Matrix 1:")
    print(inverse_matrix1)
else:
    print("\nMatrix 1 is singular (determinant is zero), so its inverse cannot be computed.")

# Rank of Matrix 1
rank_matrix1 = np.linalg.matrix_rank(matrix_1)
print("\nRank of Matrix 1:")
print(rank_matrix1)


Determinant of Matrix 1:
123.00000000000006

Inverse of Matrix 1:
[[-0.4796748   0.31707317 -0.13821138]
 [ 0.12195122 -0.09756098  0.17073171]
 [ 0.46341463 -0.17073171  0.04878049]]

Rank of Matrix 1:
3
